//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_17_Nothwind_Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpartansTable
    {
        public int PersonID { get; set; }
        public string Title { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string University { get; set; }
        public string Course { get; set; }
        public string GradeAchieved { get; set; }
        public string SpartanTutor { get; set; }
    }
}
